export const SampleData = {
    Resource: [
        {
            'Name': 'Bump/Wait List',
            'id': {
                'Assigned': true,
                'stringValue': '394ff6a8-0fa1-4793-b4f2-48e15810fc23',
                'IsGUID': true,
                'IsInt': false,
                'longValue': 394,
                'intValue': 394
            }
        }
    ],
    ChargeTicketId: [
        '1912f96c-3977-48b7-8c1c-4111de982897'
    ],
    UserDefined: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        ''
    ],
    ChargeTickets: [
        ''
    ],
    AthenaFormIds: [],
    Ins: [],
    DocIndex: [],
    FormsCompleted: [],
    PayersNoEnc: [],
    CaseIns: null,
    PreviousIds: [],
    Campaign: 0,
    CancelReason: null,
    OrigStartTimeWithOffset: '2021-08-11T19:00:00',
    StartTimeWithOffset: '2021-08-11T19:00:00',
    AllGuids: [
        '7db22829-4a89-4a82-bd2e-b75318a43379'
    ],
    Status: '',
    SpecPaymentInAdditionToCopay: false,
    AlertPayment: false,
    Deleted: false,
    SeqNbr: 0,
    IncidentToBillEncouter: false,
    CaseId: '',
    NoEncIns: false,
    PatientNoticeAnsYes: false,
    ForceTicketWayFindFile: '',
    ForceTicketPrinterSource: -842150451,
    ForceTicketPrinter: '',
    FirstConsultingId: '',
    SupervisorId: '6AA0CA8F-B8AF-4B3D-87B0-FDD5BF35F096',
    WayFindOverrideAll: false,
    WayFind: '',
    IsWalkin: false,
    PmsWalkinType: 0,
    PmsWalkin: false,
    UserId: 171,
    PracticeName: '',
    PracticeIdInt: 2,
    ApptPracticeId: '0002',
    HasAthenaScreeners: false,
    RenderingProviderId: '',
    GuidOrId: '7db22829-4a89-4a82-bd2e-b75318a43379',
    Guid: '7db22829-4a89-4a82-bd2e-b75318a43379',
    SlideId: '',
    EncounterId: '',
    DuplicateApptId: '',
    CoverageType: '',
    Complaint: '',
    LinkedAppt: false,
    Specialist: true,
    InsuranceCheckinMessage: false,
    CheckinMessage: '',
    EncounterNumber: 0,
    DeductiblePaid: {
        'CreditAmount': 0,
        'Amount': 0,
        'Pennies': 0,
        'BudgetId': '',
        'Budget': false,
        'Credit': false,
        'Defined': false,
        'Valid': false
    },
    CopayPaid: {
        'CreditAmount': 0,
        'Amount': 0,
        'Pennies': 0,
        'BudgetId': '',
        'Budget': false,
        'Credit': false,
        'Defined': false,
        'Valid': false
    },
    Copay: {
        'CreditAmount': 0,
        'Amount': 0,
        'Pennies': 0,
        'BudgetId': '',
        'Budget': false,
        'Credit': false,
        'Defined': false,
        'Valid': false
    },
    Details: '',
    TypeId: {
        'Assigned': true,
        'stringValue': '2e68cd11-f453-48cb-a54f-f1871d5aac2a',
        'IsGUID': true,
        'IsInt': false,
        'longValue': 2,
        'intValue': 2
    },
    TypeShort: 'BPC',
    Type: 'Blood Pressure Check',
    RefPrecert: 0,
    RefAuth: 0,
    SpecPayment: {
        'CreditAmount': 0,
        'Amount': 0,
        'Pennies': 0,
        'BudgetId': '',
        'Budget': false,
        'Credit': false,
        'Defined': false,
        'Valid': false
    },
    NoChargeTicket: false,
    NoInsVerify: false,
    NoCopayMsg: '',
    NoShow: false,
    NoCopay: false,
    PatientIdx: 0,
    id: {
        'Assigned': true,
        'stringValue': '37884',
        'IsGUID': false,
        'IsInt': true,
        'longValue': 37884,
        'intValue': 37884
    },
    DisallowedReason: '',
    NoInsChangeAllowed: false,
    NoBalanceRequired: false,
    AptDisallowed: false,
    OptionalInsLocation: false,
    LocationInvalidMessage: '',
    IgnoreClinicLocation: false,
    LocationValid: true,
    LocationId: {
        'Assigned': true,
        'stringValue': 'a13740b8-51b4-405b-a0b6-12dcfd3428c4',
        'IsGUID': true,
        'IsInt': false,
        'longValue': 0,
        'intValue': 0
    },
    LocationPhoneExt: '*98',
    LocationPhone: '404-886-6677',
    LocationCityStateZip: 'Hartford, WI 53027-1608',
    LocationAddr: '1032 E Sumner St',
    Location: 'Eastside Clinic',
    ServiceLocation: '',
    BillableIDIsCareProviderID: false,
    BillableProviderId: 0,
    BillableProvider: '',
    UpdateReferringProvider: false,
    RefProvider: 'Fred Barker MD',
    RefId: {
        'Assigned': true,
        'stringValue': '085cd646-4816-42f0-a10e-15d1945ef9f6',
        'IsGUID': true,
        'IsInt': false,
        'longValue': 85,
        'intValue': 85
    },
    ProviderId: {
        'Assigned': true,
        'stringValue': '8615ac69-179b-4782-a208-c9f0a052542d',
        'IsGUID': true,
        'IsInt': false,
        'longValue': 8615,
        'intValue': 8615
    },
    Provider: {
        'IsDefined': true,
        'FullNameLastFirst': 'Barclay, Joseph, MD',
        'FullName': 'Joseph Barclay MD',
        'IsResource': false,
        'Degree': 'MD',
        'Suffix': '',
        'Last': 'Barclay',
        'Middle': '',
        'First': 'Joseph'
    },
    Duration: 15,
    OrigStartTime: '2021-08-11T19:00:00',
    StartTime: '2021-08-11T19:00:00'
}
